# Generated by Django 5.2.1 on 2025-05-31 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academic_structure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст справочной информации')),
                ('file_link', models.TextField(blank=True, null=True, verbose_name='Ссылка на файл информации')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic_structure.department', verbose_name='Кафедра')),
            ],
            options={
                'verbose_name': 'Справочная информация',
                'verbose_name_plural': 'Справочная информация',
                'db_table': 'reference_info',
            },
        ),
        migrations.CreateModel(
            name='Panoramas',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('file_link', models.TextField(verbose_name='Ссылка на файл панорамы')),
                ('reference_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='excursions.referenceinfo', verbose_name='Справочная информация')),
            ],
            options={
                'verbose_name': 'Панорама',
                'verbose_name_plural': 'Панорамы',
                'db_table': 'panoramas',
            },
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Название маршрута')),
                ('matrix_file', models.TextField(verbose_name='Файл матрицы')),
                ('direction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='academic_structure.direction', verbose_name='Направление')),
                ('main_panorama', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='excursions.panoramas', verbose_name='Главная панорама')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
                'db_table': 'routes',
            },
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='Вопрос задачи')),
                ('variable_answers', models.JSONField(blank=True, null=True, verbose_name='Варианты ответов')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academic_structure.department', verbose_name='Кафедра')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'db_table': 'tasks',
            },
        ),
        migrations.AddField(
            model_name='panoramas',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='excursions.tasks', verbose_name='Задача'),
        ),
    ]
