# Generated by Django 5.2.1 on 2025-05-31 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic_structure', '0001_initial'),
        ('excursions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panorama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_id', models.CharField(max_length=100, verbose_name='ID сцены')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(upload_to='panoramas/', verbose_name='Изображение')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Панорама',
                'verbose_name_plural': 'Панорамы',
                'ordering': ['order'],
            },
        ),
        migrations.RemoveField(
            model_name='routes',
            name='main_panorama',
        ),
        migrations.RemoveField(
            model_name='routes',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='tasks',
            name='department',
        ),
        migrations.RemoveField(
            model_name='referenceinfo',
            name='file_link',
        ),
        migrations.RemoveField(
            model_name='referenceinfo',
            name='text',
        ),
        migrations.AddField(
            model_name='referenceinfo',
            name='content',
            field=models.TextField(default='', verbose_name='Содержание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referenceinfo',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Заголовок'),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='referenceinfo',
            table=None,
        ),
        migrations.CreateModel(
            name='HotSpot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pitch', models.FloatField(verbose_name='Питч')),
                ('yaw', models.FloatField(verbose_name='Яв')),
                ('type', models.CharField(max_length=50, verbose_name='Тип')),
                ('text', models.CharField(blank=True, max_length=255, verbose_name='Текст')),
                ('target_pitch', models.FloatField(blank=True, null=True, verbose_name='Целевой питч')),
                ('target_yaw', models.FloatField(blank=True, null=True, verbose_name='Целевой яв')),
                ('panorama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspots', to='excursions.panorama', verbose_name='Панорама')),
                ('target_scene', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_hotspots', to='excursions.panorama', verbose_name='Целевая сцена')),
            ],
            options={
                'verbose_name': 'Горячая точка',
                'verbose_name_plural': 'Горячие точки',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название маршрута')),
                ('first_scene', models.CharField(blank=True, max_length=100, verbose_name='Первая сцена')),
                ('direction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic_structure.direction', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршруты',
            },
        ),
        migrations.AddField(
            model_name='panorama',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panoramas', to='excursions.route', verbose_name='Маршрут'),
        ),
        migrations.DeleteModel(
            name='Panoramas',
        ),
        migrations.DeleteModel(
            name='Routes',
        ),
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
